### ISSUE TITLE
batch text to batch images

### ISSUE THREAD

**Issue by Jinx630** [gnobitab/FuseDream#6]
Hello, author, do this code support generating batch images of batch text at the same time? Instead of just generating one image for one text

**Comment by gnobitab** [comment]
Currently we only support generate one image from one text. Due to the GPU memory and time cost, we believe most of the GPUs cannot support generating two images at the same time. If you do need running it in a batch (like in our COCO experiments), we suggest to use multiple GPUs and run the one-to-one version. We actually used 16 V100 to finish our COCO experiments.
